(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)

entry[p1_,p2_,p3_]:=Block[{r=Rad[p1,p2],rr=r^2,c=Cent[p1,p2]}
	,Join[{p1,p2,r,c},
	 If[c===inf, If[p3[[1]]>p1[[1]],
		{Right,p1[[1]],p2[[1]],inf},{Left,p1[[1]],p2[[1]],inf},{yyy}]
									
	,{((p3[[1]]-c)^2+p3[[2]]^2)<rr,ArcCos[(p1[[1]]-c)/r],
		ArcCos[(p2[[1]]-c)/r],rr}, {xxx}]
]]

edges[p_]:=Block[{len=Length[p]},
	
Join[{len},
Table[entry[p[[k-2]],p[[k-1]],p[[k]] ],{k,3,len}],
{ 
entry[p[[len-1]],p[[len]],p[[1]] ],
entry[p[[len]],p[[1]],p[[2]] ]}
 ]]

