(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)

n[x_]:=N[x,20]

T=(A^2 - B^2 + C^2 - D^2)/(2*(A - B))

R=((A^2-2*A*B+B^2 + C^2 - 2*C*D + D^2)*
 
       (A^2 - 2*A*B + B^2 + C^2 + 2*C*D + D^2))^
 
   (1/2)/(2(-A + B))

Cent[w_,z_]:=Block[{A=z[[1]],B=w[[1]],C=z[[2]],D=w[[2]]},
				If[A==B,inf,n[T]]]

Rad[w_,z_]:=Block[{A=z[[1]],B=w[[1]],C=z[[2]],D=w[[2]]},
			If[A==B,inf,n[Abs[R]]]]

Distance[w_,z_]:=Block[{A=z[[1]],B=w[[1]],C=z[[2]],D=w[[2]],
				r=Rad[w,z],t=Cent[w,z]},
	{r,t	,
If[r===inf, n[Abs[Log[C/D]]],  
	 If[Positive[(A-t)/(B-t)], 
		n[Abs[Log[(r+Abs[A-t])D/C/(r+Abs[B-t]) ]]],
		n[Abs[Log[(r+Abs[A-t])/C]] +Abs[Log[(r+Abs[B-t])/D]]]
	] ,{0}] }
	]

phi[x_]:=(x+r-t)(Z-r-t)/(x-r-t)/(Z+r-t)

phiinv[x_]:=Block[{p1=phi[1],p0=phi[0],pi=(Z-r-t)/(Z+r-t)},

	(p1-pi)(x-p0)/(p1-p0)/(x-pi)]



NewPoint[{z_,w_}]:=Block[{A=z[[1]],B=w[[1]],
				C=z[[2]],D=w[[2]],
				r=Rad[w,z],t=Cent[w,z],Z=A+I*C},
	
	If[B===A, n[{B,D^2/C}], 
		Block[{NP=n[phiinv[n[phi[B+I*D]^2]]]},
			{Re[NP],Im[NP]} ],{0} ]]

